### ISSUE TITLE
Add patch level detection

### ISSUE THREAD

**Issue by Frotty** [inwc3/wc3libs#13]
I would like to move this functionality out of wurst itself.

**Comment by WaterKnight** [comment]
basic support with new class GameExe

**Comment by WaterKnight** [comment]
added GameExe.fromDir to find the right exe, tell me if it works

**Comment by Frotty** [comment]
Will try later or tomorrow, thanks.

**Comment by Frotty** [comment]
Seems good so far, but i havent tested it with pre 1.29 versions yet.
