### ISSUE TITLE
NPE on W3I.write

### ISSUE THREAD

**Issue by Frotty** [inwc3/wc3libs#23]
```
java.lang.NullPointerException
	at net.moonlightflower.wc3libs.bin.app.W3I.write_0x19(W3I.java:2040)
	at net.moonlightflower.wc3libs.bin.app.W3I.write(W3I.java:2135)
	at net.moonlightflower.wc3libs.bin.app.W3I.write(W3I.java:2152)
```

When doing a `W3I.ofMapFile(map)` on this RoC .w3m map (change ending to .w3m):
[Platform Escape 2.01xpro.zip](https://github.com/inwc3/wc3libs/files/2284731/Platform.Escape.2.01xpro.zip)

**Comment by Frotty** [comment]
Ok @WaterKnight 
This is because it's a RoC map and therefire 0x12.
The automatic write choosing 0x19 is the first error, but the second is values being written wrongly in the 0x12 format.

**Comment by WaterKnight** [comment]
can be closed?

**Comment by Frotty** [comment]
Does the attached map work? :D

**Comment by WaterKnight** [comment]
yeah, I think this was about game data set being null because 0x12 does not support it

**Comment by Frotty** [comment]
👍
