### ISSUE TITLE
Modify war3map.j values along w3I

### ISSUE THREAD

**Issue by Frotty** [inwc3/wc3libs#25]
Some stuff is represented at multiple locations.

It would be nice to have a way to generate the `InitCustomTeams`, `InitCustomPlayerSlots` and `InitAllyPriorities` from w3i entries.

Also the config parts 
```
    call SetMapName( "|cff217199Escape Builder |r[R] 0.90p" )
    call SetMapDescription( "TRIGSTR_003" )
    call SetPlayers( 12 )
    call SetTeams( 12 )
    call SetGamePlacement( MAP_PLACEMENT_TEAMS_TOGETHER )
```

**Comment by WaterKnight** [comment]
Spiking in branch jassSynth, there was/is no real support for synthesizing jass yet.

**Comment by Frotty** [comment]
As mentioned before, a bit higher level api would be highly appreciated.
I would have to merge the returned function statements with the existing functions on wurst side, which I expected wc3libs to do.
Something to the effects of:
```kotlin
val script = JassScript.of(file/mpq)
script.applyW3I(w3i)
```

**Comment by WaterKnight** [comment]
can be closed?

**Comment by Frotty** [comment]
Yes, thanks to `W3I.injectConfigsInJassScript` ❤️
