### ISSUE TITLE
get.Mdx.texture.name has unvisable char

### ISSUE THREAD

**Issue by PhoenixZeng** [inwc3/wc3libs#40]
![QQ截图20190521083500](https://user-images.githubusercontent.com/26225903/58060357-a040d580-7ba3-11e9-96d0-de43ad1b8a7b.jpg)
```
LinkedHashSet<TextureChunk> textureChunks = mdx.getTextureChunks();
for (TextureChunk textureChunk : textureChunks) {
	ArrayList<Texture> textures = textureChunk.getTextures();
	for (Texture texture : textures) {
		String fileName = texture.getFileName();
		String textureRealName = getRealName(fileName);//
		if (mpq.hasFile(fileName))
		{
			mpq.getMpqFile(fileName).extractToFile(new File(blpPath,textureRealName));
		}else{
			System.out.println(fileName);
		}
	}
}
private String getRealName(String s)
{
	String[] split = s.split("\\\\");
	return split[split.length - 1];
}
```

**Comment by Frotty** [comment]
@Water ?

**Comment by PhoenixZeng** [comment]
it is not a big deal . i looked the origin-code .  just null byte. @Frotty 
i find some mdx(usable in wc3) make exception when MDX#construct
i will report it late

**Comment by Frotty** [comment]
PR?

**Comment by PhoenixZeng** [comment]
trim() can fix it.  You might have corrected him in a second.
in Texture.getFileName()

**Comment by PhoenixZeng** [comment]
in fact . i think it should`t be trim.
because it is the `model`s set`  and trim probably make a other known problem
@Frotty

**Comment by WaterKnight** [comment]
It's stored in a constant 260 bytes. Not sure if you could theoretically have a null byte in the middle.

**Comment by PhoenixZeng** [comment]
yes. it is why think it should not be trim. @WaterKnight

**Comment by WaterKnight** [comment]
I don't think there is a point to it, just leads to errors. Encoding should
not leak through. But I can just make a 2nd getter method.

**Comment by PhoenixZeng** [comment]
if you make 2nd getter method
just handle the ends `\0`   is enough
