### ISSUE TITLE
Fix game exe detection for 1.31

### ISSUE THREAD

**Issue by Frotty** [inwc3/wc3libs#41]
the game executables are now in sub folders `x86_64` and `x86`.
Should prefer 64bit I suppose.

**Comment by WaterKnight** [comment]
It got more complex again by distinguishing between x86 and x64. I just added it as an additional method parameter you need to state for now. If we are below 1.31, the value of this boolean parameter does not matter.

**Comment by Frotty** [comment]
But how do I know if 64 version eixsts?

**Comment by Frotty** [comment]
Thanks, seems to be working now 👍
