### ISSUE TITLE
StdGameDirFinder not implemented for windows

### ISSUE THREAD

**Issue by Frotty** [inwc3/wc3libs#46]
https://github.com/inwc3/wc3libs/blob/06de7ae12ba5bd8b8869277e2c05d5f3db43b4a2/src/main/java/net/moonlightflower/wc3libs/port/StdGameDirFinder.java#L41

Is this on purpose?

https://github.com/inwc3/wc3libs/blob/3bc785f7ee61133735bfbf20ada92d8aad9421f5/src/main/java/net/moonlightflower/wc3libs/app/ObjMerger.java#L1071

ObjMerger uses it, which makes this only work on mac?

**Comment by WaterKnight** [comment]
That's weird. I am pretty sure there should be a link to WinGameDirFinder since it exists.

**Comment by Frotty** [comment]
will this be fixed?!
