### ISSUE TITLE
DOO_UNITS.Obj should be not private

### ISSUE THREAD

**Issue by PhoenixZeng** [inwc3/wc3libs#49]
just like : DOO.Dood
if it is private . then i cant modify the "war3mapUnits.doo" by code

**Comment by Frotty** [comment]
No idea what you mean. What is private?

**Comment by PhoenixZeng** [comment]
wc3libs/src/main/java/net/moonlightflower/wc3libs/bin/app/DOO_UNITS.java
line 23

**Comment by WaterKnight** [comment]
Fixed in a4d89899fe6c8947487da0a43a184c2c1bcf5ec2
