### ISSUE TITLE
what is the "id" mean? 

### ISSUE THREAD

**Issue by PhoenixZeng** [inwc3/wc3libs#50]
wc3libs/src/main/java/net/moonlightflower/wc3libs/bin/ObjMod.java. line 73
1.there are `id`,`_baseId`,`_newId` , `baseId` and `newId` is easy to know. but what is `id` mean?

2. i use this class to generate the editer-object (not by `#copy`). but the `_newId` is privated , i have to `reflect` it . i guess this class not work for generate new object?

**Comment by WaterKnight** [comment]
1. `_id = (_newId == null) ? _baseId : _newId;`

In the objMod formats of war3, there are two kinds of object blocks: Those with a baseId and without newId modify an existing object. Those with both a baseId and newId copy an existing object, then add their modifications to the new one. _baseId and _newId refer to those encodings (except that 0000 is stored as null). _id is the effective id of the object being modified, so the baseId for an original object, the newId for a custom one.

2. If it is private, you won't get it via reflection either but there are `public ObjId getId()`, `public ObjId getBaseId()`, `public ObjId getNewId()`.

**Comment by PhoenixZeng** [comment]
i get . but I still think it may be confusing. But this looks like the only way to be compatible.

whatever. now it can solve my question.

ps: about reflection . i used the declared reflect to set val
![QQ截图20191218155109](https://user-images.githubusercontent.com/26225903/71066754-3d9dcf80-21ae-11ea-9d92-25d4ce7df517.png)
