### ISSUE TITLE
can i use Multithreading read w3x or write?

### ISSUE THREAD

**Issue by qq1053831109** [inwc3/wc3libs#64]
can i use Multithreading read w3x or write?
just for Improve editing speed!

**Comment by WaterKnight** [comment]
You mean the mpq reader/writer? There are no specific multithreading facilities in this library and I have not written an own mpq reader/writer at this point. I have embedded some interfaces to be able to employ different ones, but mostly went with https://github.com/inwc3/JMPQ3 in the end. I do not think this offers much multithreading, either, but @Crigges or @Frotty can answer that better. The adapters that I have written in wc3libs at least do not heed attention to multithreading.

What you can do, of course, is put the files temporarily on the drive or somewhere else and then use JMPQ3 or another mpq reader/writer directly. Maybe you also meant to read/write multiple w3x files simultaneously, well, then you need to pay attention to shared resources and state yourself.
