### ISSUE TITLE
what is ObjMod.Obj.ExtendedMod dataPt ?

### ISSUE THREAD

**Issue by qq1053831109** [inwc3/wc3libs#65]
what is ObjMod.Obj.ExtendedMod dataPt ?

i want new a ExtendedMod  but  i dont know the dataPt is?

**Comment by WaterKnight** [comment]
That's the data pointer of the modification.

> [int: data pointer (again this int is only used by those object files that also use the level/variation int, see table*) in reality this is only used in the ability file for values that are originally stored in one of the Data columns in AbilityData.slk, this int tells the game to which of those columns the value resolves (0 = A, 1 = B, 2 = C, 3 = D, 4 = F, 5 = G, 6 = H), for example if the change applies to the column DataA3 the level int will be set to 3 and the data pointer to 0]

https://world-editor-tutorials.thehelper.net/cat_usersubmit.php?view=42787

So this must be additionally set for DataA/B/C/D/E/F/G/H modifications. If I remember correctly, it is 0 otherwise.
