### ISSUE TITLE
Is there any tool able to transform war3map.j to java?

### ISSUE THREAD

**Issue by TheXs** [inwc3/wc3libs#84]
Hi, there:
I have post the question in title.
Appreciate for any reply.

**Comment by Frotty** [comment]
It is very unclear what you mean by that, so you need to specify. If you want to parse the code into an AST, then wc3libs supports that. If you want to run Jass code in a java program, that's a completely different story and would require simulating warcraft 3 in its entirety which is something https://github.com/Retera/WarsmashModEngine does, but it's not very stable. If you just want to interpret some code into some State in a java program, https://github.com/wurstscript/WurstScript can do that. But it all depends on what you're actually trying to achieve here.

**Comment by TheXs** [comment]
> you need to specify. If you want to parse the

Thanks for reply!
Sorry for the confusion and yes, point one is exactly what I want. I will go through those antlr stuffs to see what I get.
Best regards!
